~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/affiliations.rq > dh_conferences_rdf/affiliations.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/appellations.rq > dh_conferences_rdf/appellations.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/authors.rq > dh_conferences_rdf/authors.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/authorship_affiliation.rq > dh_conferences_rdf/authorship_affiliation.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/authorships.rq > dh_conferences_rdf/authorships.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/conference_hosting_institution.rq > dh_conferences_rdf/conference_hosting_institution.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/conference_organizer.rq > dh_conferences_rdf/conference_organizer.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/conference_series.rq > dh_conferences_rdf/conference_series.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/conference_series_membership.rq > dh_conferences_rdf/conference_series_membership.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/conferences.rq > dh_conferences_rdf/conferences.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/countries.rq > dh_conferences_rdf/countries.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/institutions.rq > dh_conferences_rdf/institutions.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/keywords.rq > dh_conferences_rdf/keywords.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/languages.rq > dh_conferences_rdf/languages.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/licenses.rq > dh_conferences_rdf/licenses.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/organizers.rq > dh_conferences_rdf/organizers.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/topics.rq > dh_conferences_rdf/topics.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/work_types.rq > dh_conferences_rdf/work_types.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/works.rq > dh_conferences_rdf/works.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/works_keywords.rq > dh_conferences_rdf/works_keywords.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/works_languages.rq > dh_conferences_rdf/works_languages.ttl
~/bin/tarql-1.2/bin/tarql dh_conferences_sparql/works_topics.rq > dh_conferences_rdf/works_topics.ttl
